import Head from "next/head";
import { useState, useEffect } from "react";
import {
  Container,
  Title,
  List,
  Heading2,
  Data,
  SignupDate,
  ListContainer
} from "../components/sharedstyles";
import Cards from "../components/cards";

type SignupData = {
  id: number;
  name: string;
  email: string;
  signupDate: string;
};

type LoginData = {
  userId: number;
  date: string;
  device: string;
};

type UpgradeData = {
  userId: number;
  oldPlan: string;
  newPlan: string;
  upgradeDate: string;
};

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);
  const [signupData, setSignupData] = useState<SignupData[]>([]);
  const [loginData, setLoginData] = useState<LoginData[]>([]);
  const [upgradeData, setUpgradeData] = useState<UpgradeData[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const responseSignup = await fetch("/api/signups");
        const resultSignup = await responseSignup.json();
        setSignupData(resultSignup);

        const resLogin = await fetch("/api/logins");
        const resultLogin = await resLogin.json();
        setLoginData(resultLogin);

        const resUpgrades = await fetch("/api/upgrades");
        const resultUpgrades = await resUpgrades.json();
        setUpgradeData(resultUpgrades);

        setIsLoading(false);
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    };

    fetchData();
  }, []);

  // console.log(signupData);
  // console.log(loginData);
  // console.log(upgradeData);

  if (isLoading) <h2>Loading...</h2>;

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Title>Dashboard</Title>
        <Data>
          <span>New Users: {signupData.length}</span>
          <span>New Logins: {loginData.length}</span>
          <span>Recent upgrades: {upgradeData.length}</span>
        </Data>
        <ListContainer>
          <div>
            <Heading2>User Lists</Heading2>
            <List>
              {signupData.map((data) => {
                return (
                  <li key={data.id}>
                    <a href={`/users/${data.id}`}>
                      <span>{data.name}</span>
                      <SignupDate>Sign Up date: {data.signupDate}</SignupDate>
                    </a>
                  </li>
                );
              })}
            </List>
          </div>
        </ListContainer>
      </div>
    </Container>
  );
}
